import { EquippableType, Rarity } from "./enums";

interface Items {
    [item_id: string]: {
        resourceName: string;
        type: EquippableType;
        Rarity: Rarity;
        name: string;
        description: string;
        value: number;
    } & Record<string, any>;
}

export const items: Items = {
    //Equippables
    e1: {
        name: "Platinum Monokel",
        description: "",
        resourceName: "platinum_monocle_thick",
        Rarity: Rarity.LEGENDARY,
        type: EquippableType.EYES,
        value: 10000,
    },
    e2: {
        name: "Feines Platinum Monokel",
        description: "",
        resourceName: "platinum_monocle",
        Rarity: Rarity.LEGENDARY,
        type: EquippableType.EYES,
        value: 9500,
    },
    e3: {
        name: "Gold Monokel",
        description: "",
        resourceName: "gold_monocle_thick",
        Rarity: Rarity.EPIC,
        type: EquippableType.EYES,
        value: 5000,
    },
    e4: {
        name: "Feines Gold Monokel",
        description: "",
        resourceName: "gold_monocle",
        Rarity: Rarity.EPIC,
        type: EquippableType.EYES,
        value: 4500,
    },
    e5: {
        name: "Silber Monokel",
        description: "",
        resourceName: "silver_monocle_thick",
        Rarity: Rarity.RARE,
        type: EquippableType.EYES,
        value: 2000,
    },
    e6: {
        name: "Bronze Monokel",
        description: "",
        resourceName: "bronze_monocle_thick",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.EYES,
        value: 100,
    },
    e7: {
        name: "Linsenloses Silber Monokel",
        description: "Ring aus Alufolie mit Schnur - Bastelset",
        resourceName: "silver_monocle",
        Rarity: Rarity.COMMON,
        type: EquippableType.EYES,
        value: 10,
    },
    e8: {
        name: "Zylinderhut (Lila Textileinsatz)",
        description: "",
        resourceName: "tophat_purple_inlay",
        Rarity: Rarity.EPIC,
        type: EquippableType.HAIR,
        value: 7000,
    },
    e9: {
        name: "Zylinderhut (Roter Textileinsatz)",
        description: "",
        resourceName: "tophat_red_inlay",
        Rarity: Rarity.EPIC,
        type: EquippableType.HAIR,
        value: 600,
    },
    e10: {
        name: "Zylinderhut (Amisch) (Rot)",
        description: "",
        resourceName: "tophat_red_inlay_belt",
        Rarity: Rarity.LEGENDARY,
        type: EquippableType.HAIR,
        value: 14000,
    },
    //Hautfarben
    s1: {
        name: "Dunkel",
        description: "",
        resourceName: "dark",
        hex: "#8d5524",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.SKIN,
        value: 300,
    },
    s2: {
        name: "Braun",
        description: "",
        resourceName: "brown",
        hex: "#c68642",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.SKIN,
        value: 300,
    },
    s3: {
        name: "Gebräunt",
        description: "",
        resourceName: "browned",
        hex: "#e0ac69",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.SKIN,
        value: 300,
    },
    s4: {
        name: "Weiss",
        description: "",
        resourceName: "white",
        hex: "#f1c27d",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.SKIN,
        value: 300,
    },
    s5: {
        name: "Blass",
        description: "",
        resourceName: "pale",
        hex: "#ffdbac",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.SKIN,
        value: 300,
    },
    s6: {
        name: "Schwarz",
        description: "Aber wirklich",
        resourceName: "black",
        hex: "#000000",
        Rarity: Rarity.LEGENDARY,
        type: EquippableType.SKIN,
        value: 8000,
    },
    s7: {
        name: "Waldmeister",
        description: "Schmeckt nach Waldmeister :(",
        resourceName: "waldmeister",
        hex: "#304529",
        Rarity: Rarity.EPIC,
        type: EquippableType.SKIN,
        value: 5000,
    },
    s8: {
        name: "Minze",
        description: "Guten morgen, frisch würtzig",
        resourceName: "mint",
        hex: "#3EB489",
        Rarity: Rarity.RARE,
        type: EquippableType.SKIN,
        value: 5000,
    },
    //Gesichter
    f1: {
        name: "Selbssicherer Lächler",
        description: "Kommt einem irgendwie bekannt vor...",
        resourceName: "roblox_man_face",
        Rarity: Rarity.LEGENDARY,
        type: EquippableType.FACE,
        value: 9000,
    },
    f2: {
        name: "Schlangenmann",
        description: "Ninja-go",
        resourceName: "snake_guy_face",
        Rarity: Rarity.EPIC,
        type: EquippableType.FACE,
        value: 4000,
    },
    f3: {
        name: "Warum is ans seiner Augen größer als des andre?",
        description: "Und andere Fragen, die ich mir um 3 Uhr morgens stelle",
        resourceName: "big_eye_smal_eye_face",
        Rarity: Rarity.EPIC,
        type: EquippableType.FACE,
        value: 4500,
    },
    f4: {
        name: "Verwirrtes Gesicht",
        description: "BWM Test in einer Nussschale",
        resourceName: "clueless_face",
        Rarity: Rarity.RARE,
        type: EquippableType.FACE,
        value: 1500,
    },
    f5: {
        name: "Testgesicht",
        description: "",
        resourceName: "dummy_face",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.FACE,
        value: 700,
    },
    f6: {
        name: "Verängstigtes Gesicht",
        description: "",
        resourceName: "scared_face",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.FACE,
        value: 700,
    },
    f7: {
        name: "Müde",
        description: "Akkurate Darstellung des Bergboten-Dev-Teams",
        resourceName: "sleepy_face",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.FACE,
        value: 700,
    },
    sh1: {
        name: "Luxus Tuxedo",
        description: "",
        resourceName: "sleepy_face",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.FACE,
        value: 700,
    },
};
