import { EquippableType, Rarity } from "./enums";

interface Items {
    [item_id: string]: {
        resourceName: string;
        type: EquippableType;
        Rarity: Rarity;
        name: string;
        description: string;
        value: number;
    } & Record<string, any>;
}

export const items: Items = {
    //Equippables
    e1: {
        name: "Platinum Monokel",
        description: "",
        resourceName: "platinum_monocle_thick",
        Rarity: Rarity.LEGENDARY,
        type: EquippableType.EYES,
        value: 10000,
    },
    e2: {
        name: "Feines Platinum Monokel",
        description: "",
        resourceName: "platinum_monocle",
        Rarity: Rarity.LEGENDARY,
        type: EquippableType.EYES,
        value: 9500,
    },
    e3: {
        name: "Gold Monokel",
        description: "",
        resourceName: "gold_monocle_thick",
        Rarity: Rarity.EPIC,
        type: EquippableType.EYES,
        value: 5000,
    },
    e4: {
        name: "Feines Gold Monokel",
        description: "",
        resourceName: "gold_monocle",
        Rarity: Rarity.EPIC,
        type: EquippableType.EYES,
        value: 4500,
    },
    e5: {
        name: "Silber Monokel",
        description: "",
        resourceName: "silver_monocle_thick",
        Rarity: Rarity.RARE,
        type: EquippableType.EYES,
        value: 2000,
    },
    e6: {
        name: "Bronze Monokel",
        description: "",
        resourceName: "bronze_monocle_thick",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.EYES,
        value: 100,
    },
    e7: {
        name: "Linsenloses Silber Monokel",
        description: "Ring aus Alufolie mit Schnur - Bastelset",
        resourceName: "silver_monocle",
        Rarity: Rarity.COMMON,
        type: EquippableType.EYES,
        value: 10,
    },
    e8: {
        name: "Zylinderhut (Lila Textileinsatz)",
        description: "",
        resourceName: "tophat_purple_inlay",
        Rarity: Rarity.EPIC,
        type: EquippableType.HAIR,
        value: 7000,
    },
    e9: {
        name: "Zylinderhut (Roter Textileinsatz)",
        description: "",
        resourceName: "tophat_red_inlay",
        Rarity: Rarity.EPIC,
        type: EquippableType.HAIR,
        value: 600,
    },
    e10: {
        name: "Zylinderhut (Amisch) (Rot)",
        description: "",
        resourceName: "tophat_red_inlay_belt",
        Rarity: Rarity.LEGENDARY,
        type: EquippableType.HAIR,
        value: 14000,
    },
    e11: {
        name: "Brille",
        description: "Für jeden selbstrespektierenden Chemiker",
        resourceName: "glasses",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.EYES,
        value: 120,
    },
    e12: {
        name: "Leicht verwendete Brille",
        description: "Wenn die Versicherung mal wieder nicht greift.",
        resourceName: "broken_glasses",
        Rarity: Rarity.COMMON,
        type: EquippableType.EYES,
        value: 5,
    },
    e13: {
        name: "Bart des Kochs",
        description: "Perfekt um edle, blaue und vor allem kristalline Produkte zu kochen.",
        resourceName: "cook",
        Rarity: Rarity.EPIC,
        type: EquippableType.HAIR,
        value: 8000,
    },
    e14: {
        name: "Karenzius",
        description: "Hoch in den Bergen gibt es keine Manager.",
        resourceName: "karenzius",
        Rarity: Rarity.RARE,
        type: EquippableType.HAIR,
        value: 2000,
    },
    e15: {
        name: "Mumbo",
        description: "Stark bei den Pixeln eingespart",
        resourceName: "mumbo",
        Rarity: Rarity.RARE,
        type: EquippableType.HAIR,
        value: 2000,
    },
    e16: {
        name: "Blonder Buzz Cutt",
        description: "Traditionell Militärisch",
        resourceName: "buzz_cut_blond",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.HAIR,
        value: 250,
    },
    e17: {
        name: "Brauner Buzz Cutt",
        description: "Progressiv Militärisch",
        resourceName: "buzz_cut_brown",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.HAIR,
        value: 250,
    },
    e18: {
        name: "Wirtschaftlicher Kahlschnitt",
        description: "MEINE AUGEN",
        resourceName: "bald",
        Rarity: Rarity.EPIC,
        type: EquippableType.HAIR,
        value: 8000,
    },
    e19: {
        name: "Kopfhautinsel",
        description: "Oh mann alter",
        resourceName: "skin_island",
        Rarity: Rarity.COMMON,
        type: EquippableType.HAIR,
        value: 10,
    },
    //Hautfarben
    s1: {
        name: "Dunkel",
        description: "",
        resourceName: "dark",
        hex: "#8d5524",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.SKIN,
        value: 300,
    },
    s2: {
        name: "Braun",
        description: "",
        resourceName: "brown",
        hex: "#c68642",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.SKIN,
        value: 300,
    },
    s3: {
        name: "Gebräunt",
        description: "",
        resourceName: "browned",
        hex: "#e0ac69",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.SKIN,
        value: 300,
    },
    s4: {
        name: "Weiss",
        description: "",
        resourceName: "white",
        hex: "#f1c27d",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.SKIN,
        value: 300,
    },
    s5: {
        name: "Blass",
        description: "",
        resourceName: "pale",
        hex: "#ffdbac",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.SKIN,
        value: 300,
    },
    s6: {
        name: "Schwarz",
        description: "Aber wirklich",
        resourceName: "black",
        hex: "#000000",
        Rarity: Rarity.LEGENDARY,
        type: EquippableType.SKIN,
        value: 8000,
    },
    s7: {
        name: "Waldmeister",
        description: "Schmeckt nach Waldmeister :(",
        resourceName: "waldmeister",
        hex: "#304529",
        Rarity: Rarity.EPIC,
        type: EquippableType.SKIN,
        value: 5000,
    },
    s8: {
        name: "Minze",
        description: "Guten morgen, frisch würtzig",
        resourceName: "mint",
        hex: "#3EB489",
        Rarity: Rarity.RARE,
        type: EquippableType.SKIN,
        value: 3000,
    },
    s9: {
        name: "Blauer Kristall",
        description: "Edel, jedoch durchschaubar.",
        resourceName: "blue_crystal",
        hex: "#3EB489",
        Rarity: Rarity.EPIC,
        type: EquippableType.SKIN,
        value: 5500,
    },
    s10: {
        name: "Roter Kristall",
        description: "Authentischer \"Rubin\". Direkt aus dem Glasladen",
        resourceName: "red_crystal",
        hex: "#3EB489",
        Rarity: Rarity.EPIC,
        type: EquippableType.SKIN,
        value: 5000,
    },
    s11: {
        name: "Gold",
        description: "Man gönnt sich ja sonst nix",
        resourceName: "golden",
        hex: "#3EB489",
        Rarity: Rarity.LEGENDARY,
        type: EquippableType.SKIN,
        value: 15000,
    },
    //Gesichter
    f1: {
        name: "Selbssicherer Lächler",
        description: "Kommt einem irgendwie bekannt vor...",
        resourceName: "roblox_man_face",
        Rarity: Rarity.LEGENDARY,
        type: EquippableType.FACE,
        value: 9000,
    },
    f2: {
        name: "Schlangenmann",
        description: "Ninja-go",
        resourceName: "snake_guy_face",
        Rarity: Rarity.EPIC,
        type: EquippableType.FACE,
        value: 4000,
    },
    f3: {
        name: "Warum is ans seiner Augen größer als des andre?",
        description: "Und andere Fragen, die ich mir um 3 Uhr morgens stelle",
        resourceName: "big_eye_smal_eye_face",
        Rarity: Rarity.EPIC,
        type: EquippableType.FACE,
        value: 4500,
    },
    f4: {
        name: "Verwirrtes Gesicht",
        description: "BWM Test in einer Nussschale",
        resourceName: "clueless_face",
        Rarity: Rarity.RARE,
        type: EquippableType.FACE,
        value: 1500,
    },
    f5: {
        name: "Testgesicht",
        description: "",
        resourceName: "dummy_face",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.FACE,
        value: 700,
    },
    f6: {
        name: "Verängstigtes Gesicht",
        description: "",
        resourceName: "scared_face",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.FACE,
        value: 700,
    },
    f7: {
        name: "Müde",
        description: "Akkurate Darstellung des Bergboten-Dev-Teams",
        resourceName: "sleepy_face",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.FACE,
        value: 700,
    },
    f8: {
        name: "YOLO Klassifikator",
        description: "DSAI. JAWOL!!! DSAI!!! WOHOOO!!!",
        resourceName: "yolo_classifier",
        Rarity: Rarity.RARE,
        type: EquippableType.EYES,
        value: 4000,
    },
    f9: {
        name: "Stone Faced",
        description: "Eine osterliche Visage",
        resourceName: "stone_faced",
        Rarity: Rarity.RARE,
        type: EquippableType.FACE,
        value: 4000,
    },
    f10: {
        name: "Immense Unzufriedenheit",
        description: "Eine österreichische Visage",
        resourceName: "dissatisfaction",
        Rarity: Rarity.UNCOMMON,
        type: EquippableType.FACE,
        value: 500,
    },
    sh1: {
        name: "Reicher Bergbauer Classic",
        description: "Wenn die Alm wieder einmal ein gutes Jahr hatte...",
        resourceName: "fancy_suit",
        Rarity: Rarity.EPIC,
        type: EquippableType.SHIRT,
        value: 6000,
    },
    sh2: {
        name: "Der Harte Arbeiter",
        description: "Eine subtile Fahne vom Vorabend ist noch klar bemerkbar.",
        resourceName: "damaged_suit",
        Rarity: Rarity.COMMON,
        type: EquippableType.SHIRT,
        value: 10,
    },
    
};
